### ISSUE TITLE
Plugin not detected by Mautic 2.11

### ISSUE THREAD

**Issue by Rikk03** [thirdset/ThirdSetMauticTimingBundle#10]
Uploaded ThirdSetMauticResetBundle-Master bundle and unzipped package.
Cleared Cache.
Tried to install plugin via Mautic but plugin not detected.
-> Renamed Bundle ThirdSetMauticResetBundle
Cleared cache plugin still not detected.
-> Renamed ThirdSetMauticResetBundle to MauticThirdSetMauticResetBundle (to keep naming convention).
Still not detected.

My System
Amazon EC2 Ubuntu 16.04 + Serverpilot and with SSL cert.

**Comment by MxyzptlkFishStix** [comment]
Just tested it on a fresh install.  It works for me.

Make sure you delete the zip before clearing the cache (rm -rf cache/prod).

**Comment by collinkrawll** [comment]
I just tried it with a new install of Mautic 2.11.0 and it worked for me as well. Did you press the "Install/Upgrade Plugins" button (step 3 of the [Installation Instructions](https://github.com/thirdset/ThirdSetMauticTimingBundle#installation))?

**Comment by Rikk03** [comment]
Yes and yes.

Just checked file ownership and for some reason it says this with ls -l command

drwxrwxr-x+ 13 serverpilot ubuntu      4096 Apr 26  2017 ThirdSetMauticTimingBun                                  dle

Point is all other plugins are as follows in example

drwxr-xr-x+  7 serverpilot serverpilot 4096 Oct 27 10:43 MauticOutlookBundle

always serverpilot serverpilot

I suspect the issue is the ubuntu user however 

sudo chown -R serverpilot /srv/users/serverpilot/apps/xxxxxxx/public/plugins/ 

changes nothing ..... still Ubuntu.

How can i change it?

**Comment by Rikk03** [comment]
Never mind i figured it out.  I had to change the group using chown -h serverpilot:serverpilot and then delete the cach and it now appears.  I installed it fine thereafter.

**Comment by HOFFMACHINE** [comment]
I have trouble with working the plugin on 2.11 version... a process of installing was a success. The plugin displayed in the list of plugins but I don't see "Timing" section anywhere and feel something wrong.

Could you say what is wrong and where is the section?

**Comment by collinkrawll** [comment]
@HOFFMACHINE Please see the the [Usage section of the README file](https://github.com/thirdset/ThirdSetMauticTimingBundle#usage) for info regarding how to use the plugin. If something isn't working or if you need any help, please start a new issue and we'll be happy to help.
