### ISSUE TITLE
mautic.ERROR : CAMPAIGN: is not a valid CRON expression [] []

### ISSUE THREAD

**Issue by MattPryze** [thirdset/ThirdSetMauticTimingBundle#17]
I'm getting ```mautic.ERROR : CAMPAIGN: is not a valid CRON expression [] []``` in my log whenever my campaign tries to run. The thing is, I have not set any timings for this campaign at all. Looks like it's trying to evaluate timing on events where timing hasn't even been set.

The associated events will not fire when this occurs.

It's coming from the CronExpression.php file in this plugin, only started after the latest plugin update. Running 2.14.0

**Comment by MattPryze** [comment]
This breaks all my campaigns

**Comment by collinkrawll** [comment]
Looking at this now.

**Comment by collinkrawll** [comment]
This is fixed in [1.2.1](https://github.com/thirdset/ThirdSetMauticTimingBundle/releases/tag/1.2.1). Sorry for the trouble.

**Comment by MattPryze** [comment]
Awesome! Thanks :)
