### ISSUE TITLE
Getting a warning

### ISSUE THREAD

**Issue by moltar** [thirdset/ThirdSetMauticTimingBundle#2]
Not sure what the consequences are, but I am getting the following warning:

`$> ./app/console cache:clear`

> PHP Warning:  Declaration of MauticPlugin\ThirdSetMauticTimingBundle\Model\TimingModel::getEntity(Mautic\CampaignBundle\Entity\Event $event = NULL) should be compatible with Mautic\CoreBundle\Model\AbstractCommonModel::getEntity($id = NULL) in /var/www/mautic/mautic-2.7.1/plugins/ThirdSetMauticTimingBundle/Model/TimingModel.php on line 76

Thanks.

**Comment by collinkrawll** [comment]
This was a compatibility issue with the latest version of Mautic. It is now fixed. Please upgrade to [v1.1.2](https://github.com/thirdset/ThirdSetMauticTimingBundle/releases/tag/1.1.2) of the plugin.

Thanks for your patience and for letting us know.
