### ISSUE TITLE
Undefined offset: 0 in HoursField.php

### ISSUE THREAD

**Issue by wavelski** [thirdset/ThirdSetMauticTimingBundle#20]
I set up a campaign which goal is to send specific e-mail depending on the time of the day. I noticed e-mails are not sent.

When triggering campaign with

`php app/console mautic:campaigns:trigger`

I get:

`PHP Notice:  Undefined offset: 0 in /plugins/ThirdSetMauticTimingBundle/ThirdParty/Cron/HoursField.php on line 55`

Any ideas what goes wrong? ;)

**Comment by collinkrawll** [comment]
It sounds like your cron expression might be bad. Please see the relevant info in [this section](https://github.com/thirdset/ThirdSetMauticTimingBundle#expression-field) of the readme.

If you can paste your cron expression here I can help check it.

**Comment by collinkrawll** [comment]
Please comment back if the issue didn't end up being your cron expression and I can look into it further.
