### ISSUE TITLE
Please clarify the settings for a marketing email use case

### ISSUE THREAD

**Issue by jcmartinez** [thirdset/ThirdSetMauticTimingBundle#22]
I can't make this plugin work on **Mautic 3**. Could you clarify the settings for a marketing email use case?

I have set a campaign with emails of type "Marketing". 

My contacts all have their time zone set and they are located all over the world on different timezones.

Under Configurations > Email settings > How should email be handled? I have selected "Queue".

Within my campaign, the sending of email is configured as follows:

- Execute this event.. = Inmediatelly
- Email type = Marketing
- Timing > Expression = * 09-17 * * 1-5
- Timing > Use Contact's Time Zone? = Yes

When I run `mautic:campaigns:trigger` all messages are placed inmediatelly in the filesystem queue inside `var/spool`.

Later, when I run `mautic:emails:send` all messages go out to the SMTP server and they are removed from `var/spool`.

I would expect that only the emails directed to contacts within their current bussines hours would be generated and placed under the filesystem queue.

Could it be possible that this plugin isn't supposed to be used with filesystem queue?

Could it be possible that this pluging isn't for marketing emails, but rather for transactional emails?

Thank you for your work.

**Comment by collinkrawll** [comment]
@jcmartinez Sorry for the trouble. I just tested it and it worked for me. When you run `mautic:campaigns:trigger` what does it return? For me it shows:

```
0 total events were executed
1 total event was scheduled

Triggering scheduled events
0 total events(s) to be processed in batches of 100 contacts

0 total events were executed
0 total events were scheduled

Triggering events for inactive contacts

0 total events were executed
0 total events were scheduled
```
As can be seen above, the event is scheduled but not executed. If I then go to the Calendar in Mautic, I can see two events: one from just now when the email was triggered and one for in a couple of days for when the email is scheduled to send.

The plugin should work for both marketing and transactional emails. It should also work fine with the email queue.

**Comment by collinkrawll** [comment]
I'm going to close this. Please reply back if you have any additional questions, etc.
