### ISSUE TITLE
What is the difference between this plugin and Relative Time Period

### ISSUE THREAD

**Issue by jcmartinez** [thirdset/ThirdSetMauticTimingBundle#23]
When configuring the sending of an email with a campaign, I see the option to use a relative time period which allows selecting weekdays and hours. 

![image](https://user-images.githubusercontent.com/746915/101285435-6ff07480-37e5-11eb-9fbf-a3c497efc42f.png)

It looks like if I select the options above and I set the number of days to = 0, it is probably the same as using this plugin.

![image](https://user-images.githubusercontent.com/746915/101285693-d629c700-37e6-11eb-8989-7190a2eb7725.png)

Could you clarify the difference?

**Comment by collinkrawll** [comment]
@jcmartinez  This plugin was released in October of 2016. The Relative Time Period feature was added to Mautic core two years later in October of 2018. The core feature overlaps with much of the functionality of this plugin. If the core functionality works for your needs, I'd use that. 

Here's a couple of reasons why you might still want to use this plugin:

* Mautic core’s feature doesn’t have the full power of cron syntax. With cron syntax, you can specify things like the 1st day of the month, etc.
* Mautic’s core feature doesn’t allow you to set a specific Timezone on the Event. If the contact is in a timezone on the other side of the world, the personal email that Mautic is sending on your behalf may still get sent at 3 AM on a Sunday in your local time zone. This isn't very authentic looking. In addition, if the prospect responds right away, you may not get back to them for hours or days later when you get into the office. With this plugin you can set the email to send at 9 AM in your local timezone - the same as if you had sent it yourself.

**Comment by jcmartinez** [comment]
@collinkrawll Thank you for clarifying
