### ISSUE TITLE
Is there any way of limiting the number of messages sent when using this plugin?

### ISSUE THREAD

**Issue by jcmartinez** [thirdset/ThirdSetMauticTimingBundle#24]
I would like to send messages to my contacts during their business hours.
I also need to respect the hourly and daily sending limits of my email provider.
Would this be possible with this plugin?

**Comment by collinkrawll** [comment]
@jcmartinez I don't believe that this plugin can facilitate.

**Comment by jcmartinez** [comment]
@collinkrawll Thank you.
