### ISSUE TITLE
Clarification on the timezone

### ISSUE THREAD

**Issue by russkiimike** [thirdset/ThirdSetMauticTimingBundle#25]
Hiya,

Thanks for the plugin just trying to understand if I got this right...

I got contacts without timezones but location ips

So if I want to send emails only during Sat Sun Mon 10-13 I set the expression to

* 10-13 * * 1,6,7

And tick Contact's Time Zone

As it's supposed to fall back on the last ip address right?

**Comment by collinkrawll** [comment]
Yes, that all looks good. 

See the documentation regarding the cron expression [here](https://github.com/thirdset/ThirdSetMauticTimingBundle#expression-field) and the documentation regarding the contact's time zone [here](https://github.com/thirdset/ThirdSetMauticTimingBundle#use-contacts-time-zone-field) for details.

Also, it looks like the first asterisk in your cron expression got changed into a bullet so make sure that you start with an asterisk.

**Comment by russkiimike** [comment]
Hiya, just had a test yesterday and Mautic sent out the emails with the system timezone rather than the contact's timezone? Even though "Use contact's timezone" was enabled. It skipped the ip check? Does it count the contact's "Last accessed from" As Ip?
