### ISSUE TITLE
Does not work with Mautic 4

### ISSUE THREAD

**Issue by lucky-naty** [thirdset/ThirdSetMauticTimingBundle#26]
I have this in my logs
mautic.NOTICE: PHP Notice - date_default_timezone_set(): Timezone ID '' is invalid - in file /var/www/www-root/data/www/mautic/app/bundles/CoreBundle/EventListener/EnvironmentSubscriber.php - at line 58

It sends emails based on the contacts timezone. Despite the plugin settings in the event.

upd: Next day the PHP Notice disappeared and everything works well. Magic!

**Comment by collinkrawll** [comment]
That's odd. Myself and another plugin user just tested everything with Mautic 4 and didn't have any issues. I'm going to close this but please comment back if you are still having problems.
