### ISSUE TITLE
Table campaign_events_timing is not created

### ISSUE THREAD

**Issue by moltar** [thirdset/ThirdSetMauticTimingBundle#3]
When I'm saving the campaign, I get the following error:

> [2017-04-18 04:25:14] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'INSERT INTO campaign_events_timing (expression, use_contact_timezone, timezone, event_id) VALUES (?, ?, ?, ?)' with params ["* 09-17 * * 1-5", 0, null, 1]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic.campaign_events_timing' doesn't exist" at /var/www/mautic/mautic-2.7.1/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'INSERT INTO campaign_events_timing (expression, use_contact_timezone, timezone, event_id) VALUES (?, ?, ?, ?)' with params [\"* 09-17 * * 1-5\", 0, null, 1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic.campaign_events_timing' doesn't exist at /var/www/mautic/mautic-2.7.1/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic.campaign_events_timing' doesn't exist at /var/www/mautic/mautic-2.7.1/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic.campaign_events_timing' doesn't exist at /var/www/mautic/mautic-2.7.1/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []

Looks like the table is not created. Is there anything special I need to do to get the tables setup?

I checked with `doctrine:migrations:status` and it reports "Already at latest version".

Thanks.

**Comment by collinkrawll** [comment]
Please run these console commands to manually update your database with the changes required by the plugin:

`doctrine:schema:update --dump-sql`

Check the changes, and then run:

`doctrine:schema:update --force`

Manually updating the database like this wasn't necessary in previous versions of Mautic (v2.2.1 anyway). I've updated the README for the plugin with these instructions. Sorry for the inconvenience.

**Comment by moltar** [comment]
Thank you for the quick response!
