### ISSUE TITLE
Broken tracking link

### ISSUE THREAD

**Issue by moltar** [thirdset/ThirdSetMauticTimingBundle#4]
Oddly enough, the tracking link seems to be affected by the plugin.

When I click on the tracking link in the email, e.g.:

```
https://domain.com/r/65290d53a660fa3fb1e...JlbWFpbCI7aTozO319
```

I get the following error in the log:

> [2017-04-20 15:57:39] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function format() on null - in file /vagrant/mautic-2.7.1/plugins/ThirdSetMauticTimingBundle/Helper/TimingHelper.php - at line 94 [] []

And of course the landing page fails to load.

Thanks.

**Comment by collinkrawll** [comment]
This is now fixed in 1.1.3.

Sorry for the issue but thanks again for letting us know.
