### ISSUE TITLE
Can't install. 

### ISSUE THREAD

**Issue by mellsaid** [thirdset/ThirdSetMauticTimingBundle#6]
Hello, 

After uploading the package to the plugins folder, clearing the cache folder , the plugin doesn't install. 
Upon pressing the install/upgrade plugins, the folloding message shows: 0 new plugins were installed and 0 updated.

Mautic Version used is 2.8.2.

**Comment by collinkrawll** [comment]
Hi, sorry about that. Please try the suggestions listed here:

https://mautic.org/docs/en/tips/troubleshooting.html

If that doesn't work, let me know. The plugin has only been tested up to mautic v2.7.1 so it's possible that there is an issue with Mautic 2.8.2. If you can't get it to work, I can try installing the plugin with v2.8.2 and see if I have the same issue.

**Comment by mellsaid** [comment]
Hi @collinkrawll 

No worries and thank you. I tried the troubleshooting steps but unfortunately its the same. I didn't think there is much difference between 2.7.1 and 2.8.2 in the plugins area and our setup been working fine all around for over a year now, so dont think its related to a setup issue.  it would be great if you can try please on the new version please?

We are running PHP Version 5.6.30

**Comment by mellsaid** [comment]
Just an update, it now worked. Just for other people's reference, I originally transferred the archive to the plugins folder, and then extracted it there. Now, I just deleted the archive file, and once I've done that, the install plugins worked straight away. Seems like the existence of the zip file was hindering the system from installing the plugin..
