### ISSUE TITLE
Emails still going out outside crontab expression on mautic 2.8.2

### ISSUE THREAD

**Issue by mellsaid** [thirdset/ThirdSetMauticTimingBundle#7]
We've set the campaign and set the expression. The email still did go out on the weekend. 

Would any one be able to check it on your end / advise on this please? This plugin is a life saver if it was set to work well. 

Mautic version used is 2.8.2

![image](https://user-images.githubusercontent.com/22168697/27261586-fe00c0fc-543d-11e7-9ba1-d39b05aa3efc.png)

![image](https://user-images.githubusercontent.com/22168697/27261607-4b473df0-543e-11e7-8613-834ccdb08898.png)

**Comment by collinkrawll** [comment]
Mautic processes campaign actions for each contact in two steps. First the action is scheduled and then it is executed (the email is sent). The ThirdSetMauticTimingBundle plugin is applied when the action is **scheduled**.  So when a contact is first being processed by an action, in your above example, the contact will be placed on the Mautic calendar to receive an email 2 days from now on the first available time that fits the Monday through Friday from 8 AM to 5 PM requirement.

If the action has already been scheduled for a contact, the plugin doesn't have any effect.

My guess is that the action was already scheduled for those contacts. Can you please confirm if that is the case or not? It should work for contacts that are just getting to that action in the campaign for the first time (when they are being scheduled to receive the email).

**Comment by mellsaid** [comment]
hi @collinkrawll  Okay that make sense. I thought the plugin suppress the send out execution if it isn't within the time frames rather than act upon the scheduling triggers. I can confirm that those actions were already triggered and scheduled which would explain why. 

thank you very much for your help.

**Comment by collinkrawll** [comment]
Hi @mellsaid, no problem. We actually used to abort execution if the cron criteria wasn't met. We switched it to compute during scheduling in [v1.1.0](https://github.com/thirdset/ThirdSetMauticTimingBundle/releases/tag/1.1.0) of the plugin as that seemed to be a better way to do it and was more consistent with how Mautic was designed to work.
